### ISSUE TITLE
Doesn't render correctly when using Input Group

### ISSUE THREAD

**Issue by daniel-scatigno** [gitbrent/bootstrap4-toggle#32]
When using inside an input-group the Off button doesn't render corretly
Example:

```
                  <div class="form-group">
                    <div class='input-group'>
                        <input type="hidden" name='' value="" />
                        <input type='text' class='form-control telefone' />
                        <div class='input-group-append'>
                          <div class='input-group-btn'>
                            <input type='checkbox' class="" data-toggle='toggle'
                             value="true" data-off="Não" data-on="Sim">
                            <input type='hidden'  value="false" />
                          </div>
                      </div>
                    </div>
                  </div>

```

**Comment by bryan-brancotte** [comment]
I had the same issue, and fixed it:
``` css
.input-group .input-group-btn .toggle-on,
.input-group .input-group-btn .toggle-off{
    position: absolute;
}
```
